name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    description: 'Manually trigger a build and deploy of the site'

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Quarto CLI
      - name: Install Quarto
        run: |
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.545/quarto-1.4.545-linux-amd64.deb
          sudo dpkg -i quarto-1.4.545-linux-amd64.deb
          cd -
          rm -rf $TEMP_DIR
          quarto --version

      # Install the favorites extension (from this repo)
      - name: Install Extension
        run: |
          mkdir -p _extensions/favorites
          cp -r _extensions/favorites/* _extensions/favorites/

      # Render the site
      - name: Render Quarto Site
        run: quarto render

      # Use actions/upload-pages-artifact@v2 instead of v1
      - name: Upload GitHub Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      # For previews, we'll store the built site as a regular artifact
      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || 'main' }}
          path: _site
          retention-days: 7

  # Deploy to GitHub Pages (only for main branch)
  deploy-main:
    if: github.event_name != 'pull_request'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Deploy preview (for both main branch and PRs)
  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      # Download the preview artifact
      - name: Download preview
        uses: actions/download-artifact@v4
        with:
          name: preview-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || 'main' }}
          path: preview-download

      # Set up preview directory based on event type
      - name: Set up preview directory
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # PR preview
            PR_NUMBER=${{ github.event.pull_request.number }}
            PREVIEW_DIR="pr-preview/pr-${PR_NUMBER}"
          else
            # Main branch preview
            PREVIEW_DIR="preview"
          fi

          # Clean up existing preview
          rm -rf "${PREVIEW_DIR}" || true
          mkdir -p "${PREVIEW_DIR}"

          # Move preview to target directory
          cp -r preview-download/* "${PREVIEW_DIR}/"

          # Clean up download directory
          rm -rf preview-download

          # Store the preview dir for later steps
          echo "PREVIEW_DIR=${PREVIEW_DIR}" >> $GITHUB_ENV

      # Commit and push preview
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add "${{ env.PREVIEW_DIR }}"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            COMMIT_MSG="Update PR preview for #${{ github.event.pull_request.number }}"
          else
            COMMIT_MSG="Update preview for main branch"
          fi

          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "${COMMIT_MSG}"
          git push

      # For PRs only - find and update comment with preview link
      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Preview deployed'

      # Add or update PR comment with preview link
      - name: Create or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📝 Preview deployed to: https://ashleyhenry15.github.io/favorites/pr-preview/pr-${{ github.event.pull_request.number }}/

            Changes from this PR can be previewed at the link above. This comment will be updated automatically when new changes are pushed.
          edit-mode: replace